
package service.admin;

import entity.AppointmentType;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "Admin", targetNamespace = "http://endpoint.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Admin {


  /**
   * @param arg2
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "addAppointment", targetNamespace = "http://endpoint.me/", className = "client.AddAppointment")
  @ResponseWrapper(localName = "addAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "client.AddAppointmentResponse")
  @Action(input = "http://endpoint.me/Admin/addAppointmentRequest", output = "http://endpoint.me/Admin/addAppointmentResponse")
  boolean addAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          int arg2);

  /**
   * @param arg1
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "removeAppointment", targetNamespace = "http://endpoint.me/", className = "client.RemoveAppointment")
  @ResponseWrapper(localName = "removeAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "client.RemoveAppointmentResponse")
  @Action(input = "http://endpoint.me/Admin/removeAppointmentRequest", output = "http://endpoint.me/Admin/removeAppointmentResponse")
  String removeAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1);

  /**
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "listAppointmentAvailability", targetNamespace = "http://endpoint.me/", className = "client.ListAppointmentAvailability")
  @ResponseWrapper(localName = "listAppointmentAvailabilityResponse", targetNamespace = "http://endpoint.me/", className = "client.ListAppointmentAvailabilityResponse")
  @Action(input = "http://endpoint.me/Admin/listAppointmentAvailabilityRequest", output = "http://endpoint.me/Admin/listAppointmentAvailabilityResponse")
  String listAppointmentAvailability(
      @WebParam(name = "arg0", targetNamespace = "")
          AppointmentType arg0);

  /**
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "listLocalAppointmentAvailability", targetNamespace = "http://endpoint.me/", className = "client.ListLocalAppointmentAvailability")
  @ResponseWrapper(localName = "listLocalAppointmentAvailabilityResponse", targetNamespace = "http://endpoint.me/", className = "client.ListLocalAppointmentAvailabilityResponse")
  @Action(input = "http://endpoint.me/Admin/listLocalAppointmentAvailabilityRequest", output = "http://endpoint.me/Admin/listLocalAppointmentAvailabilityResponse")
  String listLocalAppointmentAvailability(
      @WebParam(name = "arg0", targetNamespace = "")
          AppointmentType arg0);

}
