
package service.patient;

import entity.AppointmentType;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "Patient", targetNamespace = "http://endpoint.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Patient {


  /**
   * @param arg2
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "bookAppointment", targetNamespace = "http://endpoint.me/", className = "patient.BookAppointment")
  @ResponseWrapper(localName = "bookAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "patient.BookAppointmentResponse")
  @Action(input = "http://endpoint.me/Patient/bookAppointmentRequest", output = "http://endpoint.me/Patient/bookAppointmentResponse")
  boolean bookAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          String arg2);

  /**
   * @param arg2
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "bookLocalAppointment", targetNamespace = "http://endpoint.me/", className = "patient.BookLocalAppointment")
  @ResponseWrapper(localName = "bookLocalAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "patient.BookLocalAppointmentResponse")
  @Action(input = "http://endpoint.me/Patient/bookLocalAppointmentRequest", output = "http://endpoint.me/Patient/bookLocalAppointmentResponse")
  boolean bookLocalAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          String arg2);

  /**
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getAppointmentSchedule", targetNamespace = "http://endpoint.me/", className = "patient.GetAppointmentSchedule")
  @ResponseWrapper(localName = "getAppointmentScheduleResponse", targetNamespace = "http://endpoint.me/", className = "patient.GetAppointmentScheduleResponse")
  @Action(input = "http://endpoint.me/Patient/getAppointmentScheduleRequest", output = "http://endpoint.me/Patient/getAppointmentScheduleResponse")
  public String getAppointmentSchedule(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0);

  /**
   * @param arg2
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "cancelAppointment", targetNamespace = "http://endpoint.me/", className = "patient.CancelAppointment")
  @ResponseWrapper(localName = "cancelAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "patient.CancelAppointmentResponse")
  @Action(input = "http://endpoint.me/Patient/cancelAppointmentRequest", output = "http://endpoint.me/Patient/cancelAppointmentResponse")
  public boolean cancelAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          String arg2);

  /**
   * @param arg2
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "cancelLocalAppointment", targetNamespace = "http://endpoint.me/", className = "patient.CancelLocalAppointment")
  @ResponseWrapper(localName = "cancelLocalAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "patient.CancelLocalAppointmentResponse")
  @Action(input = "http://endpoint.me/Patient/cancelLocalAppointmentRequest", output = "http://endpoint.me/Patient/cancelLocalAppointmentResponse")
  public boolean cancelLocalAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          String arg2);

  /**
   * @param arg3
   * @param arg2
   * @param arg4
   * @param arg1
   * @param arg0
   * @return returns boolean
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "swapAppointment", targetNamespace = "http://endpoint.me/", className = "patient.SwapAppointment")
  @ResponseWrapper(localName = "swapAppointmentResponse", targetNamespace = "http://endpoint.me/", className = "patient.SwapAppointmentResponse")
  @Action(input = "http://endpoint.me/Patient/swapAppointmentRequest", output = "http://endpoint.me/Patient/swapAppointmentResponse")
  boolean swapAppointment(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0,
      @WebParam(name = "arg1", targetNamespace = "")
          AppointmentType arg1,
      @WebParam(name = "arg2", targetNamespace = "")
          String arg2,
      @WebParam(name = "arg3", targetNamespace = "")
          AppointmentType arg3,
      @WebParam(name = "arg4", targetNamespace = "")
          String arg4);

  /**
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getLocalAppointmentSchedule", targetNamespace = "http://endpoint.me/", className = "patient.GetLocalAppointmentSchedule")
  @ResponseWrapper(localName = "getLocalAppointmentScheduleResponse", targetNamespace = "http://endpoint.me/", className = "patient.GetLocalAppointmentScheduleResponse")
  @Action(input = "http://endpoint.me/Patient/getLocalAppointmentScheduleRequest", output = "http://endpoint.me/Patient/getLocalAppointmentScheduleResponse")
  String getLocalAppointmentSchedule(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0);

}
